const SET_AMOUNT = "SET_AMOUNT";
const SET_CATEGORY = "SET_CATEGORY";
const SET_DIFFICULTY = "SET_DIFFICULTY";
const SET_QUESTIONS = "SET_QUESTIONS";
const SET_SCORE = "SET_SCORE";
const SET_INDEX = "SET_INDEX";
const RESET = "RESET";
const SET_ERROR = "SET_ERROR";

export default {
  SET_QUESTIONS,
  SET_AMOUNT,
  SET_CATEGORY,
  SET_DIFFICULTY,
  SET_SCORE,
  SET_INDEX,
  RESET,
  SET_ERROR,
};
